services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - mysql
      - redis  
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: voice_platform
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'  # 添加这行允许远程root连接

    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data: